name: CI/CD Pipeline

# Specify when the workflow should run
on:
  # Triggers when code is pushed to the main or master branch
  push:
    branches:
      - main
      - master
  # Triggers periodically using cron syntax
  schedule:
    - cron: '0 3 * * 1' # Runs every Monday at 3:00 AM UTC

# Define the jobs in the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Check out code
      uses: actions/checkout@v2

    # Set up JDK 11 (or the JDK version your project requires)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # Cache Maven dependencies to improve build speed
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run Maven build
    - name: Build with Maven
      run: mvn clean install

    # Run tests with Maven
    - name: Run tests
      run: mvn test
